user_config__add_uefi_grub_packages() {
	export IMAGE_PARTITION_TABLE="gpt" # GPT partition table is essential for many UEFI-like implementations, eg Apple+Intel stuff.
	export UEFISIZE=8                  #MiB - grub EFI is tiny
	export BOOTSIZE=0                  # No separate /boot
	# export FIXED_IMAGE_SIZE=4096 #MiB # should not be needed if maths are correct

	# This works for Ubuntu hirsute at least, but will be different per-OS, PR it in when you try Debian
	local UEFI_PACKAGES="os-prober grub-efi-amd64 grub-efi grub-efi-amd64-bin efibootmgr efivar"

	export PACKAGE_LIST_ADDITIONAL="${PACKAGE_LIST_ADDITIONAL} ${UEFI_PACKAGES}"
}

# @TODO: need a way to disable original initramfs creation, since that is a waste, I need to rebuild for all kernels anyway.

pre_umount_final_image__install_grub() {
	configure_grub
	local chroot_target=$MOUNT
	display_alert "Installing" "GRUB EFI" "info"
	#ls -laht "$MOUNT"/boot || true

	# disarm bomb that was planted by the bsp. @TODO: move to bsp tweaks hook
	rm -f "$MOUNT"/etc/initramfs/post-update.d/99-uboot

	# getting rid of the dtb package is hard. for now just zap it, otherwise update-grub goes bananas
	rm -rf "$MOUNT"/boot/dtb* || true

	local install_grub_cmdline="update-initramfs -c -k all && update-grub && grub-install --no-nvram --removable" # nvram is global to the host, even across chroot. take care.
	display_alert "Installing Grub EFI..." "$install_grub_cmdline" ""
	mount_chroot "$chroot_target/" # this already handles /boot/efi which is required for it to work.
	chroot "$chroot_target" /bin/bash -c "$install_grub_cmdline" || {
		echo "*** FAILED GRUB INSTALL!!!"
		echo "*** FAILED GRUB INSTALL!!!"
		echo "*** FAILED GRUB INSTALL!!!"
	}

	local root_uuid
	root_uuid=$(blkid -s UUID -o value "${LOOP}p2") # get the uuid of the root partition
	display_alert "grub-efi cfg to root part..." "uuid: ${root_uuid}" ""

	# Create /boot/efi/EFI/BOOT/grub.cfg (EFI/ESP) which will load /boot/grub/grub.cfg (in the rootfs, generated by update-grub)
	cat <<grubEfiCfg >"${MOUNT}"/boot/efi/EFI/BOOT/grub.cfg
search.fs_uuid ${root_uuid} root
set prefix=(\$root)'/boot/grub'
configfile \$prefix/grub.cfg
grubEfiCfg

	#tree "${MOUNT}"/boot

	echo "grub: "
	cat "${MOUNT}"/boot/efi/EFI/BOOT/grub.cfg

	echo "grub.cfg: "
	cat "${MOUNT}"/boot/grub/grub.cfg | grep "\/boot"

	#echo "Heres a shell in the chroot by the time we run grub."
	#chroot "$chroot_target" /bin/bash -i

	umount_chroot "$chroot_target/"

}

configure_grub() {
	cat <<EOF >>"${MOUNT}"/etc/default/grub.d/armbian-sd-uefi.cfg
GRUB_CMDLINE_LINUX_DEFAULT=" console=ttyS0 console=tty1" # extra Kernel cmdline is configured here
GRUB_TIMEOUT_STYLE=menu                                  # Show the menu...
GRUB_TIMEOUT=5                                           # ... for 5 seconds
GRUB_DISTRIBUTOR="Armbian"                               # This is a Spart^H^H^H^H^HArmbian! (will show up in some UEFI BIOS boot menu (F8?), not on others)
GRUB_DISABLE_OS_PROBER=true                              # Disable OS probing, since this is a SD card, makes no sense.
EOF
}
