source "${SRC}/fragments/hack/hack-armbian-packages.sh" # Common hacks with package lists.

# Config
export UBUNTU_KERNEL=no                # if yes, does not build our own kernel, instead, uses one from Ubuntu.
export UEFI_GRUB_TERMINAL=""           # 'serial' forces grub menu on serial console. empty to not include
export UEFI_GRUB_DISABLE_OS_PROBER=""  # 'true'  will disable os-probing, useful for SD cards.
export UEFI_GRUB_DISTRO_NAME="Armbian" # Will be used on grub menu display
export UEFI_GRUB_TIMEOUT=5             # Small timeout by default

# Hooks
user_config__add_uefi_grub_packages() {
	export IMAGE_PARTITION_TABLE="gpt"            # GPT partition table is essential for many UEFI-like implementations, eg Apple+Intel stuff.
	export UEFISIZE=256                           # in MiB - grub EFI is tiny - but some EFI BIOSes ignore small too small EFI partitions
	export BOOTSIZE=0                             # No separate /boot when using UEFI.
	export CLOUD_INIT_CONFIG_LOCATION="/boot/efi" # use /boot/efi for cloud-init as well

	# This works for Ubuntu hirsute at least, but may be different for others, PR it in when you try Debian
	# grub-efi ? only for amd64
	local UEFI_PACKAGES="os-prober grub-efi-${ARCH} grub-efi-${ARCH}-bin efibootmgr efivar"

	# Include in PACKAGE_LIST, so it gets cached in rootfs
	export PACKAGE_LIST="${PACKAGE_LIST} ${UEFI_PACKAGES}"

	if [[ "${UBUNTU_KERNEL}" == "yes" ]]; then
		export VER="generic"
		export PACKAGE_LIST_BOARD="${PACKAGE_LIST_BOARD} linux-firmware linux-image-generic"
		unset KERNELSOURCE # This should make Armbian skip most stuff. At least, I hacked it to.
	fi

	display_alert "Activating" "UEFI with SERIALCON=${SERIALCON}" ""

}

# @TODO: need a way to disable original initramfs creation, since that is a waste, I need to rebuild for all kernels anyway.

pre_umount_final_image__install_grub() {
	configure_grub
	local chroot_target=$MOUNT
	display_alert "Installing" "GRUB EFI" "info"

	# disarm bomb that was planted by the bsp. @TODO: move to bsp tweaks hook
	rm -f "$MOUNT"/etc/initramfs/post-update.d/99-uboot

	# getting rid of the dtb package is hard. for now just zap it, otherwise update-grub goes bananas
	rm -rf "$MOUNT"/boot/dtb* || true

	# add config to disable os-prober, otherwise image will have the host's other OSes boot entries.
	cat <<-grubCfgFragHostSide >>"${MOUNT}"/etc/default/grub.d/99-armbian-host-side.cfg
		GRUB_DISABLE_OS_PROBER=true
	grubCfgFragHostSide

	local install_grub_cmdline="update-initramfs -c -k all && update-grub && grub-install --no-nvram --removable" # nvram is global to the host, even across chroot. take care.
	display_alert "Installing Grub EFI..." "for all kernels" ""
	mount_chroot "$chroot_target/" # this already handles /boot/efi which is required for it to work.
	chroot "$chroot_target" /bin/bash -c "$install_grub_cmdline" >>"$DEST"/debug/install.log 2>&1 || {
		exit_with_error "${install_grub_cmdline} failed!"
	}

	# Remove host-side config.
	rm -f "${MOUNT}"/etc/default/grub.d/99-armbian-host-side.cfg

	local root_uuid
	root_uuid=$(blkid -s UUID -o value "${LOOP}p2") # get the uuid of the root partition

	# Create /boot/efi/EFI/BOOT/grub.cfg (EFI/ESP) which will load /boot/grub/grub.cfg (in the rootfs, generated by update-grub)
	cat <<-grubEfiCfg >"${MOUNT}"/boot/efi/EFI/BOOT/grub.cfg
		search.fs_uuid ${root_uuid} root
		set prefix=(\$root)'/boot/grub'
		configfile \$prefix/grub.cfg
	grubEfiCfg

	umount_chroot "$chroot_target/"

}

configure_grub() {
	display_alert "Grub EFI kernel cmdline" "console=${SERIALCON} distro=${UEFI_GRUB_DISTRO_NAME}" ""
	cat <<-grubCfgFrag >>"${MOUNT}"/etc/default/grub.d/98-armbian-sd-uefi.cfg
		GRUB_CMDLINE_LINUX_DEFAULT="console=${SERIALCON}"        # extra Kernel cmdline is configured here
		GRUB_TIMEOUT_STYLE=menu                                  # Show the menu with Kernel options (Armbian or -generic)...
		GRUB_TIMEOUT=${UEFI_GRUB_TIMEOUT}                        # ... for 5 seconds, then boot the Armbian default.
		GRUB_DISTRIBUTOR="${UEFI_GRUB_DISTRO_NAME}"              # On GRUB menu will show up as "Armbian GNU/Linux" (will show up in some UEFI BIOS boot menu (F8?) as "armbian", not on others)
	grubCfgFrag

	if [[ "a${UEFI_GRUB_DISABLE_OS_PROBER}" != "a" ]]; then
		cat <<-grubCfgFragHostSide >>"${MOUNT}"/etc/default/grub.d/98-armbian-sd-uefi.cfg
			GRUB_DISABLE_OS_PROBER=${UEFI_GRUB_DISABLE_OS_PROBER}
		grubCfgFragHostSide
	fi

	if [[ "a${UEFI_GRUB_TERMINAL}" != "a" ]]; then
		cat <<-grubCfgFragTerminal >>"${MOUNT}"/etc/default/grub.d/98-armbian-sd-uefi.cfg
			GRUB_TERMINAL=${UEFI_GRUB_TERMINAL}
		grubCfgFragTerminal
	fi

}
